export default [
  {
    inputs: [
      {
        internalType: "address",
        name: "_defaultAccountingUnit",
        type: "address",
      },
      {
        internalType: "address",
        name: "_nonfungiblePositionManagerAddress",
        type: "address",
      },
      { internalType: "address", name: "_uniswapRouter", type: "address" },
      { internalType: "address", name: "_paraswapRouter", type: "address" },
      { internalType: "address", name: "_uniswapV3factory", type: "address" },
      {
        internalType: "address",
        name: "_paraswapSwapManager",
        type: "address",
      },
      {
        internalType: "address",
        name: "_uniswapV3SwapManager",
        type: "address",
      },
      {
        internalType: "address",
        name: "_feeRecipientAddress",
        type: "address",
      },
      { internalType: "uint256", name: "_protocolFee", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "DeadlineExpired",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "EmptyContract",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount0Desired", type: "uint256" },
      { internalType: "uint256", name: "amount1Desired", type: "uint256" },
    ],
    name: "InvalidAmounts",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "InvalidBpsAmount",
    type: "error",
  },
  { inputs: [], name: "InvalidPool", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "expected", type: "address" },
      { internalType: "address", name: "received", type: "address" },
    ],
    name: "InvalidRecipient",
    type: "error",
  },
  {
    inputs: [
      { internalType: "int24", name: "tickLower", type: "int24" },
      { internalType: "int24", name: "tickUpper", type: "int24" },
    ],
    name: "InvalidTickRange",
    type: "error",
  },
  {
    inputs: [
      { internalType: "int24", name: "tickLower", type: "int24" },
      { internalType: "int24", name: "tickUpper", type: "int24" },
      { internalType: "int24", name: "spacing", type: "int24" },
    ],
    name: "InvalidTickSpacing",
    type: "error",
  },
  { inputs: [], name: "T", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "TransferLocked",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "caller", type: "address" }],
    name: "Unauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "admin",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "AdminStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "AllTransfersApprovalSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "FeesCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feesToken0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feesToken1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "protocolFee0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "protocolFee1",
        type: "uint256",
      },
    ],
    name: "PositionClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "PositionCompounded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidity",
        type: "uint128",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "PositionDecreased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidity",
        type: "uint128",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "PositionIncreased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "tickLower",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "tickUpper",
        type: "int24",
      },
    ],
    name: "PositionOpened",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "newTokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feesToken0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feesToken1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "protocolFee0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "protocolFee1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "capital0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "capital1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newTickLower",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newTickUpper",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0D",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1D",
        type: "uint256",
      },
    ],
    name: "PositionRebalanced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "PositionTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "TransferApprovalSet",
    type: "event",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "accountingUnit",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "admins",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "allTransfersApproved",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_tokenIds", type: "uint256[]" },
      { internalType: "bool", name: "_approved", type: "bool" },
    ],
    name: "approvePositionTransfers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "bytes", name: "_pSwapData0", type: "bytes" },
      { internalType: "bytes", name: "_pSwapData1", type: "bytes" },
      { internalType: "uint256", name: "_minAmountOut0", type: "uint256" },
      { internalType: "uint256", name: "_minAmountOut1", type: "uint256" },
      { internalType: "uint256", name: "_token0MaxSlippage", type: "uint256" },
      { internalType: "uint256", name: "_token1MaxSlippage", type: "uint256" },
    ],
    name: "closePosition",
    outputs: [
      { internalType: "uint256", name: "_amount0", type: "uint256" },
      { internalType: "uint256", name: "_amount1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "collectFees",
    outputs: [
      { internalType: "uint256", name: "feesToken0", type: "uint256" },
      { internalType: "uint256", name: "feesToken1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "bytes", name: "_pSwapData0", type: "bytes" },
      { internalType: "bytes", name: "_pSwapData1", type: "bytes" },
      { internalType: "uint256", name: "_minAmountOut0", type: "uint256" },
      { internalType: "uint256", name: "_minAmountOut1", type: "uint256" },
      { internalType: "uint256", name: "_token0MaxSlippage", type: "uint256" },
      { internalType: "uint256", name: "_token1MaxSlippage", type: "uint256" },
    ],
    name: "compoundPosition",
    outputs: [
      { internalType: "uint256", name: "_feesToken0", type: "uint256" },
      { internalType: "uint256", name: "_feesToken1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "uint128", name: "_amountInBPS", type: "uint128" },
      { internalType: "bytes", name: "_pSwapData0", type: "bytes" },
      { internalType: "bytes", name: "_pSwapData1", type: "bytes" },
      { internalType: "uint256", name: "_minAmountOut0", type: "uint256" },
      { internalType: "uint256", name: "_minAmountOut1", type: "uint256" },
      { internalType: "uint256", name: "_token0MaxSlippage", type: "uint256" },
      { internalType: "uint256", name: "_token1MaxSlippage", type: "uint256" },
    ],
    name: "decreaseLiquidity",
    outputs: [
      { internalType: "uint256", name: "_amount0", type: "uint256" },
      { internalType: "uint256", name: "_amount1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAccountingUnit",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeRecipientAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
    name: "getPositionInfo",
    outputs: [
      { internalType: "address", name: "token0", type: "address" },
      { internalType: "address", name: "token1", type: "address" },
      { internalType: "uint8", name: "token0Decimals", type: "uint8" },
      { internalType: "uint8", name: "token1Decimals", type: "uint8" },
      { internalType: "uint256", name: "feesEarned0", type: "uint256" },
      { internalType: "uint256", name: "feesEarned1", type: "uint256" },
      { internalType: "uint256", name: "protocolFee0", type: "uint256" },
      { internalType: "uint256", name: "protocolFee1", type: "uint256" },
      { internalType: "uint256", name: "principal0", type: "uint256" },
      { internalType: "uint256", name: "principal1", type: "uint256" },
      { internalType: "address", name: "ownerAccountingUnit", type: "address" },
      {
        internalType: "uint8",
        name: "ownerAccountingUnitDecimals",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "uint256", name: "_amountAdd0", type: "uint256" },
      { internalType: "uint256", name: "_amountAdd1", type: "uint256" },
      { internalType: "uint256", name: "_token0MaxSlippage", type: "uint256" },
      { internalType: "uint256", name: "_token1MaxSlippage", type: "uint256" },
    ],
    name: "increaseLiquidity",
    outputs: [
      { internalType: "uint128", name: "_liquidity", type: "uint128" },
      { internalType: "uint256", name: "_amount0", type: "uint256" },
      { internalType: "uint256", name: "_amount1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nonfungiblePositionManager",
    outputs: [
      {
        internalType: "contract INonfungiblePositionManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "token0", type: "address" },
          { internalType: "address", name: "token1", type: "address" },
          { internalType: "uint24", name: "fee", type: "uint24" },
          { internalType: "int24", name: "tickLower", type: "int24" },
          { internalType: "int24", name: "tickUpper", type: "int24" },
          { internalType: "uint256", name: "amount0Desired", type: "uint256" },
          { internalType: "uint256", name: "amount1Desired", type: "uint256" },
          { internalType: "uint256", name: "amount0Min", type: "uint256" },
          { internalType: "uint256", name: "amount1Min", type: "uint256" },
          { internalType: "address", name: "recipient", type: "address" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
        ],
        internalType: "struct INonfungiblePositionManager.MintParams",
        name: "_params",
        type: "tuple",
      },
      { internalType: "address", name: "owner", type: "address" },
    ],
    name: "openPosition",
    outputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "uint128", name: "liquidity", type: "uint128" },
      { internalType: "uint256", name: "amount0", type: "uint256" },
      { internalType: "uint256", name: "amount1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "owners",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "protocolFee",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "uint256", name: "_token0MaxSlippage", type: "uint256" },
      { internalType: "uint256", name: "_token1MaxSlippage", type: "uint256" },
      { internalType: "int24", name: "_lowerRangeDistribution", type: "int24" },
      { internalType: "int24", name: "_upperRangeDistribution", type: "int24" },
    ],
    name: "rebalancePosition",
    outputs: [
      { internalType: "uint256", name: "_feesToken0", type: "uint256" },
      { internalType: "uint256", name: "_feesToken1", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "routers",
    outputs: [
      { internalType: "address", name: "uniswapRouter", type: "address" },
      { internalType: "address", name: "paraswapRouter", type: "address" },
      { internalType: "address", name: "uniswapV3factory", type: "address" },
      { internalType: "address", name: "paraswapSwapManager", type: "address" },
      {
        internalType: "address",
        name: "uniswapV3SwapManager",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_accountingUnit", type: "address" },
    ],
    name: "setAccountingUnit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_admin", type: "address" }],
    name: "setAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "_approved", type: "bool" }],
    name: "setAllTransfersApproved",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_defaultAccountingUnit",
        type: "address",
      },
    ],
    name: "setDefaultAccountingUnit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_feeRecipientAddress",
        type: "address",
      },
    ],
    name: "setFeeRecipientAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_protocolFee", type: "uint256" },
    ],
    name: "setProtocolFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "transferApproved",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "address", name: "_newOwner", type: "address" },
    ],
    name: "transferPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
